services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile

    container_name: seo-api-gateway

    ports:
      - "5100:5000"

    env_file:
      - .env

    depends_on:
      - seo-content
      - seo-onpage
      - seo-technical

    networks:
      - seo-network

    restart: unless-stopped


  seo-content:
    build:
      context: ./services/seo-content

    container_name: seo-content-service

    ports:
      - "5103:5003"

    env_file:
      - .env

    networks:
      - seo-network

    restart: unless-stopped


  seo-onpage:
    build:
      context: ./services/seo-onpage

    container_name: seo-onpage-service

    ports:
      - "5104:5004"

    env_file:
      - .env

    networks:
      - seo-network

    restart: unless-stopped


  seo-technical:
    build:
      context: ./services/seo-technical

    container_name: seo-technical-service

    ports:
      - "5105:5005"

    env_file:
      - .env

    networks:
      - seo-network

    restart: unless-stopped


networks:
  seo-network:
    external: true